services:
  db:
    image: mysql:8
    container_name: o3o-db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - o3o_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 10
      timeout: 10s


  backend:
    # 이미지는 환경 변수로 관리
    image: ${REGISTRY_URL}/o3o-backend:${TAG}
    # build:
    #   context: ./backend
    #   dockerfile: /Dockerfile
    container_name: o3o-backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - o3o_network

volumes:
  db_data:

networks:
  o3o_network:
    name: o3o_network
    driver: bridge
